//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POCOModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sys_dic> sys_dic { get; set; }
        public DbSet<set_allhouse_price> set_allhouse_price { get; set; }
        public DbSet<set_card> set_card { get; set; }
        public DbSet<set_card_upgrade> set_card_upgrade { get; set; }
        public DbSet<set_hourhouse_price> set_hourhouse_price { get; set; }
        public DbSet<set_house_type> set_house_type { get; set; }
        public DbSet<set_inte_house> set_inte_house { get; set; }
        public DbSet<set_integral> set_integral { get; set; }
        public DbSet<set_otherhouse_price> set_otherhouse_price { get; set; }
        public DbSet<sys_function> sys_function { get; set; }
        public DbSet<sys_menu> sys_menu { get; set; }
        public DbSet<sys_org> sys_org { get; set; }
        public DbSet<sys_role> sys_role { get; set; }
        public DbSet<sys_role_function> sys_role_function { get; set; }
        public DbSet<sys_role_menu> sys_role_menu { get; set; }
        public DbSet<sys_role_user> sys_role_user { get; set; }
        public DbSet<sys_user> sys_user { get; set; }
        public DbSet<user_access_log> user_access_log { get; set; }
        public DbSet<user_login_log> user_login_log { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<set_inte_exchange> set_inte_exchange { get; set; }
    }
}
