//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets080B2BE9320DD4D0D86EB5128899356A7B4854DB2D98555C73A951DF04C0C29A))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySets080B2BE9320DD4D0D86EB5128899356A7B4854DB2D98555C73A951DF04C0C29A : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySets080B2BE9320DD4D0D86EB5128899356A7B4854DB2D98555C73A951DF04C0C29A()
        {
            this.EdmEntityContainerName = "Entities";
            this.StoreEntityContainerName = "ModelStoreContainer";
            this.HashOverMappingClosure = "de3e90a42a53eaa299baa817e621986ebdf365fa4882b545776f304182e98d22";
            this.HashOverAllExtentViews = "9365e84ddb488b24a9f1f29f492de35e70e57f3e8471145409d47818a9529d6e";
            this.ViewCount = 2;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for ModelStoreContainer.sys_dic
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.sys_dic", @"
    SELECT VALUE -- Constructing sys_dic
        [Model.Store.sys_dic](T1.[sys_dic.Id], T1.[sys_dic.DicName], T1.[sys_dic.ParentId], T1.[sys_dic.CreateAt])
    FROM (
        SELECT 
            T.Id AS [sys_dic.Id], 
            T.DicName AS [sys_dic.DicName], 
            T.ParentId AS [sys_dic.ParentId], 
            T.CreateAt AS [sys_dic.CreateAt], 
            True AS _from0
        FROM Entities.sys_dic AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for Entities.sys_dic
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Entities.sys_dic", @"
    SELECT VALUE -- Constructing sys_dic
        [Model.sys_dic](T1.[sys_dic.Id], T1.[sys_dic.DicName], T1.[sys_dic.ParentId], T1.[sys_dic.CreateAt])
    FROM (
        SELECT 
            T.Id AS [sys_dic.Id], 
            T.DicName AS [sys_dic.DicName], 
            T.ParentId AS [sys_dic.ParentId], 
            T.CreateAt AS [sys_dic.CreateAt], 
            True AS _from0
        FROM ModelStoreContainer.sys_dic AS T
    ) AS T1");
        }
    }
}
