//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POCOModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sys_dic> sys_dic { get; set; }
        public virtual DbSet<set_allhouse_price> set_allhouse_price { get; set; }
        public virtual DbSet<set_card> set_card { get; set; }
        public virtual DbSet<set_card_upgrade> set_card_upgrade { get; set; }
        public virtual DbSet<set_hourhouse_price> set_hourhouse_price { get; set; }
        public virtual DbSet<set_house_type> set_house_type { get; set; }
        public virtual DbSet<set_inte_house> set_inte_house { get; set; }
        public virtual DbSet<set_integral> set_integral { get; set; }
        public virtual DbSet<set_otherhouse_price> set_otherhouse_price { get; set; }
    }
}
