//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POCOModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class set_allhouse_price
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> HalfPriceHours { get; set; }
        public Nullable<int> AllPriceHours { get; set; }
        public string LeaveTime { get; set; }
        public Nullable<int> AddFeeHours { get; set; }
        public string AddFeeType { get; set; }
        public string AddAllDay { get; set; }
        public Nullable<int> AddAllHours { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public string CreatedBy { get; set; }
    }
}
