//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POCOModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class set_hourhouse_price
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<int> HalfPriceHours { get; set; }
        public string CheckInTime1 { get; set; }
        public string CheckInTime2 { get; set; }
        public Nullable<int> AddBuffTime { get; set; }
        public Nullable<int> TurnNormal { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public string CreatedBy { get; set; }
    }
}
