//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POCOModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_dic
    {
        public int Id { get; set; }
        public string DicName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsValid { get; set; }
    }
}
