//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.App.Model.SYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class set_house_type : IEntityBase
    {
        public int Id { get; set; }
        public string TypeName { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool IsValid { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<decimal> AllPrice { get; set; }
        public Nullable<decimal> StartPrice { get; set; }
        public Nullable<decimal> AddPrice { get; set; }
        public Nullable<decimal> AddMaxPrice { get; set; }
        public Nullable<decimal> PreReceiveFee { get; set; }
        public string Remark { get; set; }
    }
}
