//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.App.Model.SYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class set_group : IEntityBase
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string LinkMan { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string ContractNo { get; set; }
        public Nullable<System.DateTime> ContractDate1 { get; set; }
        public Nullable<System.DateTime> ContractDate2 { get; set; }
        public Nullable<decimal> AccountFee { get; set; }
        public string AccountNo { get; set; }
        public string Seller { get; set; }
        public Nullable<int> Coupons { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool IsValid { get; set; }
        public string CreatedBy { get; set; }
    }
}
