//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.App.Model.Sale
{
    using System;
    using System.Collections.Generic;
    
    public partial class yx_book : IEntityBase
    {
        public int Id { get; set; }
        public string OrderNo { get; set; }
        public string CusName { get; set; }
        public string Mobile { get; set; }
        public string IDCard { get; set; }
        public string Status { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<System.DateTime> BookTime { get; set; }
        public Nullable<System.DateTime> ReachTime { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<System.DateTime> LeaveTime { get; set; }
        public Nullable<System.DateTime> RetainTime { get; set; }
        public string CheckInType { get; set; }
        public string CheckInMode { get; set; }
        public string Channels { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public string BatchNo { get; set; }
        public string Saller { get; set; }
        public string OrderTaker { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool IsValid { get; set; }
        public string CreatedBy { get; set; }
    }
}
