//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.App.Model.Sale
{
    using System;
    using System.Collections.Generic;
    
    public partial class yx_booklist : IEntityBase
    {
        public int Id { get; set; }
        public string OrderNo { get; set; }
        public Nullable<int> HouseType { get; set; }
        public string HouseCode { get; set; }
        public string PriceActive { get; set; }
        public string PriceProject { get; set; }
        public Nullable<decimal> HousePrice { get; set; }
        public string Remark { get; set; }
    }
}
